name: Build

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

jobs:
  build-and-test:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create Build
        run: docker build -t build:base -f ./.github/Build.Dockerfile .
      - name: Copy build to host
        run: mkdir dist && docker run -v $PWD:/opt/mount --rm --entrypoint cp build:base -R /app/dist /opt/mount/dist
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: dist